# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  IMAGE_NAME: resource-manager-front
  CONTAINER_NAME: resource-manager-front

tasks:
  dev:
    desc: "Run the development environment"
    cmds:
      - docker build -f Dockerfile -t {{.IMAGE_NAME}}-dev .
      - >
        docker run -it --rm 
        --name {{.CONTAINER_NAME}}-dev 
        -p 5173:5173 
        -v {{.PWD}}:/app 
        -v /app/node_modules 
        {{.IMAGE_NAME}}-dev
